# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodCup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodCup
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'SnapKit', '~> 4.0.0'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'TextFieldEffects'
  pod 'AlamofireImage', '~> 3.5'
  pod 'PopupDialog', '~> 0.9'
  pod 'Hero'
  pod 'DCAnimationKit'
  pod 'CircleMenu'
  pod 'RHSideButtons'

end
